services:
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-unitraffic}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-unitraffic}
      POSTGRES_USER: ${POSTGRES_USER:-unitraffic}
    volumes:
    - db-data:/var/lib/postgresql/data:rw
    ports:
    - 5432:5432

  adminer:
    image: dockette/adminer:pgsql
    restart: always
    ports:
    - target: 80
      published: 5400
      protocol: tcp

volumes:
  db-data:
